use_frameworks!

platform :ios, '10.0'

target 'TPUIKit-Swift_Example' do
  pod 'TPUIKit-Swift', :path => '../'
  pod 'SnapKit'
  target 'TPUIKit-Swift_Tests' do
    inherit! :search_paths

    
  end
end
